import os

MYSQL_DATABASE_HOST = os.getenv('MYSQL_DATABASE_HOST')
MYSQL_DATABASE_USER = os.getenv('MYSQL_DATABASE_USER')
MYSQL_DATABASE_PASSWORD = os.getenv('MYSQL_DATABASE_PASSWORD')
MYSQL_DATABASE_DB = os.getenv('MYSQL_DATABASE_DB')
SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG_TB_ENABLED = os.getenv('DEBUG_TB_ENABLED').lower() == 'true'
DEBUG_TB_INTERCEPT_REDIRECTS = os.getenv('DEBUG_TB_INTERCEPT_REDIRECTS').lower == 'true'
DEBUG_TB_PROFILER_ENABLED = os.getenv('DEBUG_TB_PROFILER_ENABLED').lower() == 'true'